#!/bin/bash

#Update system
sudo apt-get update
sudo apt-get -y dist-upgrade
sudo apt-get install -y whois
sudo apt -y autoremove
sudo apt -y autoclean

#Install the abstraction layers
wget -O - https://github.com/wildlife-systems/sound-device-control/raw/master/install | sudo bash
wget -O - https://github.com/Wildlife-Systems/image-device-control/raw/master/install | sudo bash
wget -O - https://github.com/wildlife-systems/pi-pwr/raw/master/install | sudo bash


#Set defaults
SECURITY="manual"
SNDDEV="manual"
IMGDEV="manual"
PASSWD="manual"

#Check if device is registered or should run as standalone
#replace manuals above with settings

#Security: Default password
PWSALT=`sudo grep pi /etc/shadow | awk -F\$ '{print $3}'`
PWPI=`sudo grep pi /etc/shadow | awk -F: '{print $2}'`
PWDFT=`mkpasswd -m sha-512 raspberry $PWSALT`

#Security: Firewall
if [[ "$PASSWD" == "manual" ]]; then
  if [[ "$PWPI" == "$PWDFT" ]]; then
    echo "Default password (raspberry) is in use for user pi. This must be changed."
    passwd
  fi
fi

#Setup sound device
if [[ "$SNDDEV" == "manual" ]]; then
  sdc-inst list
  echo $""
  echo "Select sound device to install:"
  read SNDDEV
fi
sdc-inst $SNDDEV

#Setup imaging device
if [[ "$IMGDEV" == "manual" ]]; then
  idc-inst list
  echo $""
  echo "Select camera to install:"
  read IMGDEV
fi
idc-inst $IMGDEV

#Install runtime script

#Save settings to file

#Reboot
