#!/bin/bash

I=`ps -A | grep aao-run | wc -l`
if [[ $I -gt 2 ]]; then
	exit 0
fi

#Config
CONFIG=$(cat /home/pi/.aao.conf)
COUNTDOWN=5
FNTYPE=$(echo "$CONFIG" | jq -r '.init .filenaming')

function onOff {
  pi-pwr off $(echo "$CONFIG" | jq -r '.init .off[]' | tr '\n' ' ')
  pi-pwr on $(echo "$CONFIG" | jq -r '.init .on[]' | tr '\n' ' ')
}

if [[ "$1" != "cron" ]]; then
  aao-heartbeat countdown&
  echo Preparing to run...
  aao-indicate countdown $COUNTDOWN
  aao-indicate heartbeat &
fi



while true;
do

case $FNTYPE in
        timestamp)
                FN=$(date +%s)
                ;;
        *)
                echo "Incorrect filename pattern"
                exit 1;
                ;;
esac


	N=$(echo "$CONFIG" | jq -r ".run | length")
	I=0
	while [ $I  -lt $N ];
	do
		pi-pwr off $(echo "$CONFIG" | jq -r ".run[$I] .off[]" | tr '\n' ' ')
  		pi-pwr on $(echo "$CONFIG" | jq -r ".run[$I] .on[]" | tr '\n' ' ')
		ACTION=`echo $CONFIG| jq -r ".run[$I] .action"`
		echo $ACTION
		aao-heartbeat $ACTION &
        	case  $ACTION in
			record)
				DURATION=`echo $CONFIG| jq -r ".run[$I] .duration"`
				CHANNELS=`echo $CONFIG| jq -r ".run[$I] .channels"`
				BITRATE=`echo $CONFIG| jq -r ".run[$I] .bitrate"`
				FORMAT=`echo $CONFIG| jq -r ".run[$I] .format"`
				aao-indicate record "arecord -c $CHANNELS -r $BITRATE -f $FORMAT -d $DURATION $FN.wav"
				;;
			sleep)
				sleep `echo $CONFIG| jq -r ".run[$I] .duration"`
				;;
			upload)
				;;
			upload-delete)
				METHOD=`echo $CONFIG| jq -r ".run[$I] .method"`
				UPPATH=`echo $CONFIG| jq -r ".run[$I] .path"`
				EXTENSION=`echo $CONFIG| jq -r ".run[$I] .extension"`
				ASYNC=`echo $CONFIG| jq -r ".run[$I] .async"`
				case $METHOD in
					s3cmd)
						S3UP=`eval echo "s3cmd put $FN.$EXTENSION s3://$UPPATH"`
						S3UP="$S3UP && rm $FN.$EXTENSION"
						if [[ "$ASYNC" == "true" ]]; then
						  S3UP="( $S3UP )&";
						fi
						eval $S3UP
						;;
				esac
				;;
			clearup)
				;;
		esac

		I=$(($I + 1))
		aao-indicate heartbeat
	onOff
	done
#Exit after one iteration if called form cron
if [[ "$1" == "cron" ]]; then
	exit 0
fi
done
