#!/bin/bash

#Update system
sudo apt-get update
sudo apt-get -y dist-upgrade
sudo apt-get install -y whois ufw jq
sudo apt -y autoremove
sudo apt -y autoclean

#Install the abstraction layers
wget -O - https://github.com/wildlife-systems/sound-device-control/raw/master/install | sudo bash
wget -O - https://github.com/Wildlife-Systems/image-device-control/raw/master/install | sudo bash
wget -O - https://github.com/wildlife-systems/pi-pwr/raw/master/install | sudo bash

#Set defaults
DEVNAME="raspberrypi"
SNDDEV="manual"
IMGDEV="manual"
PASSWD="manual"
FIREWALL="manual"

#Device serial
AAOSERIAL=`grep Serial /proc/cpuinfo | cut -d ' ' -f 2`

#Check if device is registered or should run as standalone
URL="https://devices.wildlife.systems/info/?id=$AAOSERIAL"
response=$(curl -s -w "\n%{http_code}" $URL)
http_code=$(tail -n1 <<< "$response")  # get the last line
content=$(sed '$ d' <<< "$response")   # get all but the last line which contains the status code
if [[ $http_code == "200" ]]; then
  echo "Device found on https://devices.wildlife.systems - proceeding with automated setup"
  DEVNAME=`echo $content | jq -r '."device-name"'`
  SNDDEV=`echo $content | jq -r '."sound-device"'`
  IMGDEV=`echo $content | jq -r '."camera-type"'`
  FIREWALL=`echo $content | jq -r '."firewall"'`
else
  echo "No matching device serial number found on https://devices.wildlife.systems"
  echo "If  you want to add it before proceeding the serial number is $AAOSERIAL."
fi

#Security: Default password
PWSALT=`sudo grep pi /etc/shadow | awk -F\$ '{print $3}'`
PWPI=`sudo grep pi /etc/shadow | awk -F: '{print $2}'`
PWDFT=`mkpasswd -m sha-512 raspberry $PWSALT`
if [[ "$PASSWD" == "manual" ]]; then
  if [[ "$PWPI" == "$PWDFT" ]]; then
    echo "Default password (raspberry) is in use for user pi. This must be changed."
    passwd
  fi
fi

#Security: Firewall
if [[ "$FIREWALL" == "manual" ]]; then
  echo $""
  echo "Allow SSH through the firewall? (y/n)"
  read ALLOWSSH
  if [[ "$ALLOWSSH" == "y" ]]; then
    sudo ufw allow ssh
  fi
  echo y | sudo ufw enable
else
  if [[ "$FIREWALL" == "allow-ssh-in" ]]; then
    sudo ufw allow ssh
    echo y | sudo ufw enable
  fi
fi

#Setup hostname

#Setup sound device
if [[ "$SNDDEV" == "manual" ]]; then
  sdc-inst list
  echo $""
  echo "Select sound device to install:"
  read SNDDEV
fi
sdc-inst $SNDDEV

#Setup imaging device
if [[ "$IMGDEV" == "manual" ]]; then
  idc-inst list
  echo $""
  echo "Select camera to install:"
  read IMGDEV
fi
idc-inst $IMGDEV

#Install runtime script

#Save settings to file

#Reboot
echo $""
echo "Press enter to reboot"
read REBOOT
sudo reboot
