#!/bin/bash

# WildlifeSystems
#
# This script is part of the WildlifeSystems project. For further information
# please refer to https://docs.wildlife.systems, or for more information on
# the project itself, please refer to https://wildlife.systems.

# Return codes
#
# Further information on WildlifeSystems standard reurn codes can be found
# at https://docs.wildlife.systems/return-codes.html
# 0 - Success
# 10 - invalid argument


while [[ $(pgrep -f ws-indicate | wc -l) -gt 2 ]]; do
  sleep 0.1
done

#Initial state
ATINIT=`awk -F'[][]' '{print $2}' /sys/class/leds/led0/trigger`
ABINIT=`cat /sys/class/leds/led0/brightness`

MODEL=$(grep -oP 'Revision\s*:\s*\K[^ ]*' /proc/cpuinfo)
if [[ "$MODEL" != "000d" ]]; then
  PTINIT=`awk -F'[][]' '{print $2}' /sys/class/leds/led1/trigger`
  PBINIT=`cat /sys/class/leds/led1/brightness`
fi

#Indicators
case "$1" in
	list)
		echo $ATINIT
		echo $ABINIT
		echo $PTINIT
		echo $PBINIT
		exit 0
		;;

	heartbeat)
		for in in {1..2}; do
			pi-pwr on actled &
			pi-pwr off pwrled &
			sleep 0.1
			pi-pwr on pwrled &
			pi-pwr off actled
			sleep 0.1
			x=$(( $x + 1 ))
		done
		;;

	countdown)
		pi-pwr off actled &
		for i in $(seq $2 -1 0); do
			pi-pwr off pwrled &
			sleep 0.5
			pi-pwr on pwrled &
			sleep 0.5
			echo $i
		done
		;;

	record)
		pi-pwr off actled &
		pi-pwr on pwrled &
		$2
		pi-pwr off pwrled &
		;;

	*)
		exit 10
esac

#Restore initial state
echo $ABINIT | sudo tee /sys/class/leds/led0/brightness >> /dev/null
echo $ATINIT | sudo tee /sys/class/leds/led0/trigger >> /dev/null

if [[ "$MODEL" != "000d" ]]; then
  echo $PBINIT | sudo tee /sys/class/leds/led1/brightness >> /dev/null
  echo $PTINIT | sudo tee /sys/class/leds/led1/trigger >> /dev/null
fi
