#!/bin/bash
set -e

# Stop and disable the systemd service
systemctl stop ws-audio.service || true
systemctl disable ws-audio.service || true

systemctl stop ws-sensors.service || true
systemctl disable ws-sensors.service || true

exit 0