.TH WS-INDICATE 1 "January 2026" "ws-node 1.4.1" "WildlifeSystems Commands"
.SH NAME
ws-indicate \- control status indicator for WildlifeSystems node
.SH SYNOPSIS
.B ws-indicate
.RI [ status ]
.SH DESCRIPTION
.B ws-indicate
controls the status indicator (LED or similar) on a WildlifeSystems node
to provide visual feedback about the node's current state.
.SH ARGUMENTS
.TP
.I status
The status to indicate.
.SH SEE ALSO
.BR ws-heartbeat (1),
.BR ws-network (1)
.SH AUTHOR
Ed Baker <ed@ebaker.me.uk>
.SH COPYRIGHT
Copyright \(co 2024-2026 Ed Baker.
License GPLv2+: GNU GPL version 2 or later.
