.TH WS-NETWORK 1 "January 2026" "ws-node 1.4.1" "WildlifeSystems Commands"
.SH NAME
ws-network \- manage network configuration for WildlifeSystems node
.SH SYNOPSIS
.B ws-network
.SH DESCRIPTION
.B ws-network
manages network connectivity for WildlifeSystems nodes, handling
connection setup and monitoring.
.SH SEE ALSO
.BR ws-setup (1),
.BR ws-heartbeat (1),
.BR ws-indicate (1)
.SH AUTHOR
Ed Baker <ed@ebaker.me.uk>
.SH COPYRIGHT
Copyright \(co 2024-2026 Ed Baker.
License GPLv2+: GNU GPL version 2 or later.
