.TH WS-SETUP 1 "January 2026" "ws-node 1.4.1" "WildlifeSystems Commands"
.SH NAME
ws-setup \- initial setup for WildlifeSystems node
.SH SYNOPSIS
.B ws-setup
.SH DESCRIPTION
.B ws-setup
performs initial configuration and setup of a WildlifeSystems node,
including hardware detection and service configuration.
.SH SEE ALSO
.BR ws-network (1),
.BR ws-run-audio (1),
.BR ws-run-sensors (1)
.SH AUTHOR
Ed Baker <ed@ebaker.me.uk>
.SH COPYRIGHT
Copyright \(co 2024-2026 Ed Baker.
License GPLv2+: GNU GPL version 2 or later.
